/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package systemzarzadzaniarecepcja;

import java.sql.Connection;

import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;

import javax.swing.JOptionPane;

/**
 *
 * @author Hubert
 */
public class Pracownik extends javax.swing.JFrame {

    private static String idPracownikaUsun;

    public Pracownik() {
        setSize(800, 600);
        setLocationRelativeTo(null);
        initComponents();
        Logowanie logowanie = new Logowanie();

        labelZalogowano1.setText(logowanie.przekazLogin());
        WyczyscOkno();
    }

    private void WyczyscOkno() {
        textfieldLogin.setText("");
        textfieldImie.setText("");
        textfieldNazwisko.setText("");
        ftextfieldPesel.setText("");
        ftextfieldNrTel.setText("");
        textfieldEmail.setText("");
        textfieldWyszukaj.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGlowny = new javax.swing.JPanel();
        panelTytulowy = new javax.swing.JPanel();
        labelTytulowy = new javax.swing.JLabel();
        buttonWyjscie = new javax.swing.JButton();
        labelZalogowano = new javax.swing.JLabel();
        panelOpcji = new javax.swing.JPanel();
        panelDodajPracownika = new javax.swing.JTabbedPane();
        panelEdytuj = new javax.swing.JPanel();
        labelImie = new javax.swing.JLabel();
        labelPlec = new javax.swing.JLabel();
        labelPesel = new javax.swing.JLabel();
        labelNrtelefonu = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        textfieldImie = new javax.swing.JTextField();
        textfieldNazwisko = new javax.swing.JTextField();
        textfieldEmail = new javax.swing.JTextField();
        comboPlec = new javax.swing.JComboBox<>();
        buttonUsun = new javax.swing.JButton();
        buttonZmien = new javax.swing.JButton();
        buttonWyszukaj = new javax.swing.JButton();
        textfieldWyszukaj = new javax.swing.JTextField();
        labelNazwisko = new javax.swing.JLabel();
        labelIdLubPesel = new javax.swing.JLabel();
        ftextfieldNrTel = new javax.swing.JFormattedTextField();
        ftextfieldPesel = new javax.swing.JFormattedTextField();
        buttonDodaj = new javax.swing.JButton();
        labelImie1 = new javax.swing.JLabel();
        textfieldLogin = new javax.swing.JTextField();
        buttonWyczysc = new javax.swing.JButton();
        labelZalogowano1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelGlowny.setBackground(new java.awt.Color(255, 255, 255));

        panelTytulowy.setBackground(new java.awt.Color(51, 51, 51));

        labelTytulowy.setFont(new java.awt.Font("Cambria", 1, 48)); // NOI18N
        labelTytulowy.setForeground(new java.awt.Color(255, 255, 255));
        labelTytulowy.setText("Pracownik");

        javax.swing.GroupLayout panelTytulowyLayout = new javax.swing.GroupLayout(panelTytulowy);
        panelTytulowy.setLayout(panelTytulowyLayout);
        panelTytulowyLayout.setHorizontalGroup(
            panelTytulowyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTytulowyLayout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(labelTytulowy)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTytulowyLayout.setVerticalGroup(
            panelTytulowyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTytulowyLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(labelTytulowy)
                .addContainerGap())
        );

        buttonWyjscie.setBackground(new java.awt.Color(51, 51, 51));
        buttonWyjscie.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        buttonWyjscie.setForeground(new java.awt.Color(255, 255, 255));
        buttonWyjscie.setText("Wróć");
        buttonWyjscie.setBorderPainted(false);
        buttonWyjscie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonWyjscieMouseClicked(evt);
            }
        });

        labelZalogowano.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        labelZalogowano.setForeground(new java.awt.Color(0, 0, 0));
        labelZalogowano.setText("Zalogowano jako");

        panelOpcji.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout panelOpcjiLayout = new javax.swing.GroupLayout(panelOpcji);
        panelOpcji.setLayout(panelOpcjiLayout);
        panelOpcjiLayout.setHorizontalGroup(
            panelOpcjiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelOpcjiLayout.setVerticalGroup(
            panelOpcjiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        panelDodajPracownika.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        panelEdytuj.setBackground(new java.awt.Color(51, 51, 51));
        panelEdytuj.setForeground(new java.awt.Color(51, 51, 51));

        labelImie.setBackground(new java.awt.Color(255, 255, 255));
        labelImie.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        labelImie.setForeground(new java.awt.Color(255, 255, 255));
        labelImie.setText("Imie:");

        labelPlec.setBackground(new java.awt.Color(255, 255, 255));
        labelPlec.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        labelPlec.setForeground(new java.awt.Color(255, 255, 255));
        labelPlec.setText("Płeć:");

        labelPesel.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        labelPesel.setForeground(new java.awt.Color(255, 255, 255));
        labelPesel.setText("Pesel:");

        labelNrtelefonu.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        labelNrtelefonu.setForeground(new java.awt.Color(255, 255, 255));
        labelNrtelefonu.setText("Numer telefonu:");

        labelEmail.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        labelEmail.setForeground(new java.awt.Color(255, 255, 255));
        labelEmail.setText("Adres e-mail:");

        textfieldImie.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N

        textfieldNazwisko.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N

        textfieldEmail.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N

        comboPlec.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        comboPlec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kobieta", "Mezczyzna" }));

        buttonUsun.setBackground(new java.awt.Color(51, 51, 51));
        buttonUsun.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        buttonUsun.setForeground(new java.awt.Color(255, 255, 255));
        buttonUsun.setText("Usuń");
        buttonUsun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUsunActionPerformed(evt);
            }
        });

        buttonZmien.setBackground(new java.awt.Color(51, 51, 51));
        buttonZmien.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        buttonZmien.setForeground(new java.awt.Color(255, 255, 255));
        buttonZmien.setText("Zmień");
        buttonZmien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonZmienActionPerformed(evt);
            }
        });

        buttonWyszukaj.setBackground(new java.awt.Color(51, 51, 51));
        buttonWyszukaj.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        buttonWyszukaj.setForeground(new java.awt.Color(255, 255, 255));
        buttonWyszukaj.setText("Wyszukaj");
        buttonWyszukaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonWyszukajActionPerformed(evt);
            }
        });

        textfieldWyszukaj.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N

        labelNazwisko.setBackground(new java.awt.Color(255, 255, 255));
        labelNazwisko.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        labelNazwisko.setForeground(new java.awt.Color(255, 255, 255));
        labelNazwisko.setText("Nazwisko:");

        labelIdLubPesel.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        labelIdLubPesel.setForeground(new java.awt.Color(255, 255, 255));
        labelIdLubPesel.setText("ID lub PESEL pracownika:");

        ftextfieldNrTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#########"))));
        ftextfieldNrTel.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N

        ftextfieldPesel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###########"))));
        ftextfieldPesel.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N

        buttonDodaj.setBackground(new java.awt.Color(51, 51, 51));
        buttonDodaj.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        buttonDodaj.setForeground(new java.awt.Color(255, 255, 255));
        buttonDodaj.setText("Dodaj");
        buttonDodaj.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDodajActionPerformed(evt);
            }
        });

        labelImie1.setBackground(new java.awt.Color(255, 255, 255));
        labelImie1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        labelImie1.setForeground(new java.awt.Color(255, 255, 255));
        labelImie1.setText("Login:");

        textfieldLogin.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        textfieldLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEdytujLayout = new javax.swing.GroupLayout(panelEdytuj);
        panelEdytuj.setLayout(panelEdytujLayout);
        panelEdytujLayout.setHorizontalGroup(
            panelEdytujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEdytujLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEdytujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonWyszukaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textfieldWyszukaj)
                    .addComponent(labelIdLubPesel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(panelEdytujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEdytujLayout.createSequentialGroup()
                        .addGroup(panelEdytujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelEdytujLayout.createSequentialGroup()
                                .addComponent(buttonDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonUsun, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonZmien, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelEdytujLayout.createSequentialGroup()
                                .addGroup(panelEdytujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelNrtelefonu)
                                    .addComponent(labelEmail))
                                .addGap(21, 21, 21)
                                .addGroup(panelEdytujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ftextfieldNrTel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textfieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(40, 40, 40))
                    .addGroup(panelEdytujLayout.createSequentialGroup()
                        .addGroup(panelEdytujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelEdytujLayout.createSequentialGroup()
                                .addGroup(panelEdytujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelPesel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelPlec, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelImie, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelNazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(67, 67, 67)
                                .addGroup(panelEdytujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelEdytujLayout.createSequentialGroup()
                                        .addComponent(comboPlec, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(textfieldImie)
                                    .addComponent(ftextfieldPesel)
                                    .addComponent(textfieldNazwisko, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(panelEdytujLayout.createSequentialGroup()
                                .addComponent(labelImie1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(textfieldLogin)))
                        .addGap(167, 167, 167))))
        );
        panelEdytujLayout.setVerticalGroup(
            panelEdytujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEdytujLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelEdytujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelIdLubPesel)
                    .addGroup(panelEdytujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelImie1)
                        .addComponent(textfieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelEdytujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEdytujLayout.createSequentialGroup()
                        .addComponent(textfieldWyszukaj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonWyszukaj))
                    .addGroup(panelEdytujLayout.createSequentialGroup()
                        .addGroup(panelEdytujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelImie)
                            .addComponent(textfieldImie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEdytujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textfieldNazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNazwisko))
                        .addGap(6, 6, 6)
                        .addGroup(panelEdytujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboPlec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPlec))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEdytujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPesel)
                            .addComponent(ftextfieldPesel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEdytujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ftextfieldNrTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNrtelefonu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEdytujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textfieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEdytujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonUsun, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonZmien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(79, 79, 79))
        );

        panelDodajPracownika.addTab("Zarządzaj", panelEdytuj);

        buttonWyczysc.setBackground(new java.awt.Color(51, 51, 51));
        buttonWyczysc.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        buttonWyczysc.setForeground(new java.awt.Color(255, 255, 255));
        buttonWyczysc.setText("Wyczyść okno");
        buttonWyczysc.setBorderPainted(false);
        buttonWyczysc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonWyczyscActionPerformed(evt);
            }
        });

        labelZalogowano1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        labelZalogowano1.setForeground(new java.awt.Color(0, 0, 0));
        labelZalogowano1.setText("Zalogowano jako");

        javax.swing.GroupLayout panelGlownyLayout = new javax.swing.GroupLayout(panelGlowny);
        panelGlowny.setLayout(panelGlownyLayout);
        panelGlownyLayout.setHorizontalGroup(
            panelGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTytulowy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelGlownyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelZalogowano)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelZalogowano1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonWyczysc, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonWyjscie, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
            .addComponent(panelOpcji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelDodajPracownika)
        );
        panelGlownyLayout.setVerticalGroup(
            panelGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlownyLayout.createSequentialGroup()
                .addComponent(panelTytulowy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelOpcji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelDodajPracownika)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonWyjscie, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelZalogowano)
                    .addComponent(buttonWyczysc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelZalogowano1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGlowny, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGlowny, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonWyjscieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonWyjscieMouseClicked
        new Menu().setVisible(rootPaneCheckingEnabled);
        dispose();
    }//GEN-LAST:event_buttonWyjscieMouseClicked

    private void buttonUsunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUsunActionPerformed
        Connection con;
        PreparedStatement pst;
        String imie = textfieldImie.getText();
        String nazwisko = textfieldNazwisko.getText();
        String pesel = ftextfieldPesel.getText();
        String numerTelefonu = ftextfieldNrTel.getText();
        String email = textfieldEmail.getText();
        String login = textfieldLogin.getText();

        if (imie.isEmpty() || nazwisko.isEmpty() || pesel.isEmpty() || numerTelefonu.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Pola nie mogą być puste.");
        } else if (pesel.length() != 11) {
            JOptionPane.showMessageDialog(null, "Błędny numer PESEL.");
        } else if (numerTelefonu.length() != 9) {
            JOptionPane.showMessageDialog(null, "Błędny numer telefonu.");
        } else if (JOptionPane.showConfirmDialog(null, "Czy na pewno usunąć pracownika?", "Usuwanie pracownika",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            try {
                String szukaneDane = textfieldWyszukaj.getText();
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql:///systemzarzadzaniarecepcja", "root", "password");
                pst = con.prepareStatement("SET FOREIGN_KEY_CHECKS=0;");
                int wynik1 = pst.executeUpdate();
                pst = con.prepareStatement("DELETE FROM logowanie WHERE id_pracownik ='" + idPracownikaUsun + "';");
                int wynik2 = pst.executeUpdate();
                pst = con.prepareStatement("DELETE FROM pracownik WHERE login ='" + login + "'AND imie='" + imie + "'AND nazwisko='" + nazwisko + "'AND pesel='" + pesel + "'AND numer_telefonu='" + numerTelefonu + "'AND email='" + email + "';");
                int wynik3 = pst.executeUpdate();
                WyczyscOkno();
                JOptionPane.showMessageDialog(null, "Pomyślnie usunięto z bazy.");
                pst.close();
                con.close();
            } catch (Exception ee) {
                JOptionPane.showMessageDialog(null, "Dany pracownik nie istnieje w bazie.");
            }
        }

    }//GEN-LAST:event_buttonUsunActionPerformed

    private void buttonZmienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonZmienActionPerformed
        Connection con;
        PreparedStatement pst;

        String imie = textfieldImie.getText();
        String nazwisko = textfieldNazwisko.getText();
        String pesel = ftextfieldPesel.getText();
        String numerTelefonu = ftextfieldNrTel.getText();
        String email = textfieldEmail.getText();
        String plec = comboPlec.getSelectedItem().toString();
        if (plec.equals("Mezczyzna")) {
            plec = "m";
        } else {
            plec = "k";
        }
        String szukaneDane = textfieldWyszukaj.getText();
        if (imie.isEmpty() || nazwisko.isEmpty() || pesel.isEmpty() || numerTelefonu.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Pola nie mogą być puste.");
        } else if (pesel.length() != 11) {
            JOptionPane.showMessageDialog(null, "Błędny numer PESEL.");
        } else if (numerTelefonu.length() != 9) {
            JOptionPane.showMessageDialog(null, "Błędny numer telefonu.");
        } else
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql:///systemzarzadzaniarecepcja", "root", "password");
            pst = con.prepareStatement("UPDATE pracownik SET imie='" + imie + "' , nazwisko='" + nazwisko + "' , plec ='" + plec + "' ,pesel='" + pesel + "' ,numer_telefonu='" + numerTelefonu + "' , email='" + email + "' WHERE id = '" + szukaneDane + "' OR pesel='" + szukaneDane + "';");
            int wynik1 = pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Dane pracownika zostały zaktualizowane.");
            WyczyscOkno();
            con.close();
        } catch (Exception ee) {}
    }//GEN-LAST:event_buttonZmienActionPerformed

    private void buttonWyszukajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonWyszukajActionPerformed
        String szukaneDane = textfieldWyszukaj.getText();
        Connection con;
        ResultSet rs;
        PreparedStatement pst;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql:///systemzarzadzaniarecepcja", "root", "password");
            pst = con.prepareStatement("SELECT * From pracownik WHERE id ='" + szukaneDane + "' OR pesel='" + szukaneDane + "'");
            rs = pst.executeQuery();
            if (rs.next()) {
                idPracownikaUsun = rs.getString("id");
                String plec = rs.getString("plec");
                if (plec.equals("m")) {
                    comboPlec.setSelectedItem("Mezczyzna");
                } else if (plec.equals("k")) {
                    comboPlec.setSelectedItem("Kobieta");
                }
                textfieldLogin.setText(rs.getString("login"));
                textfieldImie.setText(rs.getString("imie"));
                textfieldNazwisko.setText(rs.getString("nazwisko"));
                ftextfieldPesel.setText(rs.getString("pesel"));
                ftextfieldNrTel.setText(rs.getString("numer_telefonu"));
                textfieldEmail.setText(rs.getString("email"));
            } else {
                JOptionPane.showMessageDialog(null, "Pracownik o podanych danych nie istnieje.");
            }
            rs.close();
            con.close();
        } catch (Exception ee) {  }
    }//GEN-LAST:event_buttonWyszukajActionPerformed

    private void buttonWyczyscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonWyczyscActionPerformed

        WyczyscOkno();

    }//GEN-LAST:event_buttonWyczyscActionPerformed

    private void buttonDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDodajActionPerformed

        Connection con;
        PreparedStatement pst;
        ResultSet rs;
        String imie = textfieldImie.getText();
        String nazwisko = textfieldNazwisko.getText();
        String pesel = ftextfieldPesel.getText();
        String numerTelefonu = ftextfieldNrTel.getText();
        String email = textfieldEmail.getText();
        String plec = comboPlec.getSelectedItem().toString();
        String login = textfieldLogin.getText();
        String idPracownika = null;

        if (imie.isEmpty() || nazwisko.isEmpty() || pesel.isEmpty() || numerTelefonu.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Pola nie mogą być puste.");
        } else if (pesel.length() != 11) {
            JOptionPane.showMessageDialog(null, "Błędny numer PESEL.");
        } else if (numerTelefonu.length() != 9) {
            JOptionPane.showMessageDialog(null, "Błędny numer telefonu.");
        } else try {
            if (plec.equals("Mezczyzna")) {
                plec = "m";
            } else {
                plec = "k";
            }
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql:///systemzarzadzaniarecepcja", "root", "password");
            String sql = "INSERT INTO pracownik (login,imie,nazwisko,plec,pesel,numer_telefonu,email,data_utworzenia) VALUES('" + login + "','" + imie + "','" + nazwisko + "','" + plec + "','" + pesel + "','" + numerTelefonu + "','" + email + "',CURRENT_DATE" + ");";
            pst = con.prepareStatement(sql);
            int wynik1 = pst.executeUpdate();
            String sql2 = "SELECT id from pracownik order by id desc limit 1";
            pst = con.prepareStatement(sql2);
            rs = pst.executeQuery();
            if (rs.next()) {
                idPracownika = rs.getString(1);
            }
            String sql3 = "INSERT INTO logowanie(id_pracownik) VALUES('" + idPracownika + "');";
            pst = con.prepareStatement(sql3);
            int wynik2 = pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Nowy pracownik o ID " + idPracownika + " został dodany.");
            WyczyscOkno();
            con.close();
        } catch (Exception ee) {
            JOptionPane.showMessageDialog(null, "Osoba o podanych danych już istnieje w bazie.");
        }
    }//GEN-LAST:event_buttonDodajActionPerformed

    private void textfieldLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pracownik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pracownik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pracownik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pracownik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pracownik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDodaj;
    private javax.swing.JButton buttonUsun;
    private javax.swing.JButton buttonWyczysc;
    private javax.swing.JButton buttonWyjscie;
    private javax.swing.JButton buttonWyszukaj;
    private javax.swing.JButton buttonZmien;
    private javax.swing.JComboBox<String> comboPlec;
    private javax.swing.JFormattedTextField ftextfieldNrTel;
    private javax.swing.JFormattedTextField ftextfieldPesel;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelIdLubPesel;
    private javax.swing.JLabel labelImie;
    private javax.swing.JLabel labelImie1;
    private javax.swing.JLabel labelNazwisko;
    private javax.swing.JLabel labelNrtelefonu;
    private javax.swing.JLabel labelPesel;
    private javax.swing.JLabel labelPlec;
    private javax.swing.JLabel labelTytulowy;
    private javax.swing.JLabel labelZalogowano;
    private javax.swing.JLabel labelZalogowano1;
    private javax.swing.JTabbedPane panelDodajPracownika;
    private javax.swing.JPanel panelEdytuj;
    private javax.swing.JPanel panelGlowny;
    private javax.swing.JPanel panelOpcji;
    private javax.swing.JPanel panelTytulowy;
    private javax.swing.JTextField textfieldEmail;
    private javax.swing.JTextField textfieldImie;
    private javax.swing.JTextField textfieldLogin;
    private javax.swing.JTextField textfieldNazwisko;
    private javax.swing.JTextField textfieldWyszukaj;
    // End of variables declaration//GEN-END:variables
}
